# Generated by Django 5.1.13 on 2025-11-03 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto de seña'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_status',
            field=models.CharField(choices=[('pending', 'Pendiente de verificación'), ('verified', 'Verificada')], default='pending', max_length=12, verbose_name='Estado de seña'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transferencia bancaria'), ('mercadopago', 'Mercado Pago'), ('cash', 'Efectivo en el local')], default='transfer', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Referencia de pago'),
        ),
    ]
